Grpc server
v4dikos1/CityTalk.UserService pull request #4
Opened 2024-11-06 16:02 UTC by N1ghtmarex

добавлен gRPC-сервер - заглушка

2024-11-07 09:31 UTC, v4dikos1 requested changes

2024-11-07 09:31 UTC, v4dikos1 commented on CityTalk.UserService/Api/Dockerfile
> +FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
Смерджи мастер ветку, пожалуйста. Чтобы не добавлять по несколько раз одно и то же

2024-11-07 09:31 UTC, v4dikos1 commented on CityTalk.UserService/Api/Program.cs
> +Environment.SetEnvironmentVariable("ConnectionString", builder.Configuration.GetConnectionString("DbContext"));
в ServiceRegistrar

2024-11-12 06:07 UTC, N1ghtmarex commented on CityTalk.UserService/Api/Dockerfile
> +FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
не пон)

2024-11-12 06:07 UTC, N1ghtmarex commented on CityTalk.UserService/Api/Program.cs
> +Environment.SetEnvironmentVariable("ConnectionString", builder.Configuration.GetConnectionString("DbContext"));
исправил

2024-11-12 14:21 UTC, v4dikos1 approved these changes

2024-11-12 14:21 UTC, merged